import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Header from "@/components/layout/Header/Header";
import Footer from "@/components/layout/Footer/footer";
import AuthProvider from "@/components/Context/AuthProvider";

import "./globals.css";

const montserrat = Montserrat({
    subsets: ["latin"],
    weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={montserrat.className}
                style={{ backgroundColor: "black", minHeight: "100vh" }}
            >
                <main className="max-w-[1170px]  mx-auto ">
                    <AuthProvider>
                        <Header></Header>
                        {children}
                        <Footer></Footer>
                    </AuthProvider>
                </main>
            </body>
        </html>
    );
}
